### ISSUE TITLE
Using a camera to read the hydrometer?

### ISSUE THREAD

**Issue by Mark-Kiwi** [larry-athey/rpi-smart-still#3]
Hey Larry! Great work by the way...I've been following this project and have recently purchased a t-500 still with the intention of building your system and give this brewing hobby a go. (It's legal where I'm from).
I noted the change you have made from load cell to the TOF sensor which got me thinking about if there might be any other way to get accurate hydrometer readings....then came up with the brainwave of why not have the RPI read the hydrometer using a camera???? 
I've seen some projects where people use a RPI and camera and a package called OpenCV to identify objects etc.
Doing more googling I found some instances where people use a camera to measure object sizes, and one where a guy was able to read an dial dial type gauge. Maybe some smart cookie can figure out how to take the actual hydrometer reading. The camera could be mounted in such a position where it's line of sight sits at the top of the parrot so it can identify where the fluid meets the hydrometer. Light levels could be kept constant with some inbuilt lighting...should give a repeatable output and best of all....no moving parts! 
It's beyond my skills, but possibly someone out there could figure it out....then it would just be a case of merging it into your system.
The only issue I can think off might be the processing requirements might be too hard on the pi. Would love to hear your thoughts....

**Comment by larry-athey** [comment]
The problem with that is that the hydrometer rotates and optical character recognition needs the hydrometer to be oriented so that the numbers are always facing the camera.

**Comment by Mark-Kiwi** [comment]
Yeah I had thought about that and came up with two possibile sollutions...
One was to station mirrors either side and behind the hydrometer so the camera has 360 field of view (surely it could be coded to read a reflected/reversed image.) 
Or secondly, imagine something like half a vertical tube placed behind the hydrometer and a lightweight horizontal rod attached to the hydrometer. The hydrometer would still be free to move up and down vertically, but if it rotated, the rod would touch the half tube and stop it rotating the scale away from the camera. 
:-)

**Comment by larry-athey** [comment]
I did a lot of research on this when I first decided to come up with something that was easier for people to build than the load cell hydrometer. I abandoned this idea because it would be even more difficult because of the optics involved and the limitations of the optical character recognition libraries. On top of those limitations, counting the lines between the visible number and the distillate was a completely different obstacle outside of optical character recognition and not something that I really wanted to put a year or more into figuring out.

If somebody else wants to take a crack at it, making it work with the system is just a matter of them outputting the reading at 9600 baud serial every 10 to 15 seconds. Just follow the text format as shown at the tail end of the load cell or LIDAR hydrometer code. I just don't have the spare time to put into figuring that out and how to make it simple enough for non-geek types to build.

Granted, non-geek types couldn't build the LIDAR hydrometer reader either. But, I can build it and send it to somebody so all they have to do is attach it to their parrot. The guy who designed the RPi "Hat" circuit board made things way easier to build and the LIDAR hydrometer reader simplifies things even further. If somebody else can figure out how to make an optical hydrometer reader that's also easy to build, I'd happily add it to the repository here. It's just not something that I have the time for in my schedule.
